# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3.7'

services:
  # Redis Proxy service
  proxy-service:
    # Configuration for building the docker image for the redis proxy service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    depends_on:
      - redis # This service depends on Redis. Start that first.

    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - common

  # Redis service
  redis:
    image: naviter/redis-6.0.4-alpine
    ports:
      - "6379:6379"
    networks:
      - common

  e2e-tests:
    build:
      context: e2e-tests
      dockerfile: Dockerfile
    depends_on:
      - redis
      - proxy-service
    networks:
      - common

## Networks to be created to facilitate communication between containers
networks:
  common:
